version: 2
jobs:
  testpy2:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 2.7 Tests 
          command: |
            tox -e py27-18,py27-110,py27-111

  testpy34:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.4 Tests 
          command: |
            tox -e py34-18,py34-110,py34-111,34-2,34-21

  testpy35:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.5 Tests 
          command: |
            tox -e py35-18,py35-110,py35-111,34-2,34-21

  testpy36:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.6 Tests 
          command: |
            tox -e py36-111,34-2,34-21

workflows:
  version: 2
  test_pys:
    jobs:
      - testpy2
      - testpy34
      - testpy35
      - testpy36
